"""this should work

Revision ID: 32272ae435c2
Revises: 60512b165b86
Create Date: 2023-05-16 15:23:20.892711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32272ae435c2'
down_revision = '60512b165b86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
