"""updated page name to service name

Revision ID: d5fd0c708ec6
Revises: e3321aa657d4
Create Date: 2023-05-16 15:29:54.739859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fd0c708ec6'
down_revision = 'e3321aa657d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagediscount', sa.Column('service_name', sa.String(), nullable=False))
    op.drop_column('pagediscount', 'page_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagediscount', sa.Column('page_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pagediscount', 'service_name')
    # ### end Alembic commands ###
