"""omo eh

Revision ID: e3321aa657d4
Revises: 5228edab877c
Create Date: 2023-05-16 15:28:30.539270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3321aa657d4'
down_revision = '5228edab877c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagediscount', sa.Column('page_name', sa.String(), nullable=False))
    op.drop_column('pagediscount', 'service_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagediscount', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pagediscount', 'page_name')
    # ### end Alembic commands ###
